"""add token blacklist

Revision ID: 08a3de2f8d8e
Revises: 37597f392d6a
Create Date: 2026-01-02 23:21:39.529295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08a3de2f8d8e'
down_revision = '37597f392d6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expired_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=512),
               existing_nullable=False)
        batch_op.create_unique_constraint(
                    "uq_token_blacklist_token",
                    ["token"]
                )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('token',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
        batch_op.drop_constraint(
                "uq_token_blacklist_token",
                type_="unique"
            )


    # ### end Alembic commands ###
