"""add created_at to users

Revision ID: a65a9a03129d
Revises: a73ed49b5200
Create Date: 2026-01-06 11:25:19.024089

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a65a9a03129d'
down_revision = 'a73ed49b5200'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('ADMIN', 'USER', name='userrole'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('ADMIN', 'USER', name='userrole'),
               type_=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
