"""add email to users

Revision ID: a73ed49b5200
Revises: 08a3de2f8d8e
Create Date: 2026-01-03 22:17:38.127115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a73ed49b5200'
down_revision = '08a3de2f8d8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('telphone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sensors', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_unique_constraint(None, ['telphone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('sensors')
        batch_op.drop_column('telphone')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
